# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Troll Control India
tagline:          'Control The Troll In You'
description:      'Helping Increase the Health of Conversations on Twitter'
url:              https://trollcontrolindia.com
baseurl:          '/lanyon'

author:
  name:           'Troll Control India'
  url:            https://twitter.com/TrollControl_in

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/monoprague/lanyon
